# This workflow will initiate a Veracode Static Analysis Pipeline scan, return a results.json and convert to SARIF for upload as a code scanning alert

name: Veracode Static Analysis Pipeline Scan

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-pipeline-scan:
    runs-on: ubuntu-latest
    steps:
    
    - uses: actions/checkout@v2
      with:
        repository: ''
  
    - name: Build with Maven
      run: mvn clean verify
    
    - uses: actions/upload-artifact@v1
      with:
        name: my-artifact
        path: target/verademo.war
    
    # download the Veracode Static Analysis Pipeline scan jar
    - uses: wei/curl@master
      with:
        args: -O https://downloads.veracode.com/securityscan/pipeline-scan-LATEST.zip
    - run: unzip -o pipeline-scan-LATEST.zip
    
    - uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - run: java -jar pipeline-scan.jar --veracode_api_id "${{secrets.VERACODE_API_ID}}" --veracode_api_key "${{secrets.VERACODE_API_SECRET}}" --fail_on_severity="Very High, High" --file verademo.war
      continue-on-error: true
    - name: Convert pipeline scan output to SARIF format 
      id: convert
      uses: veracode/veracode-pipeline-scan-results-to-sarif@master
      with:
        pipeline-results-json: results.json
    - uses: github/codeql-action/upload-sarif@v1
      with:
        # Path to SARIF file relative to the root of the repository
        sarif_file: veracode-results.sarif
